0	390	<div xmlns="http://www.tei-c.org/ns/1.0">
33	69	<l xmlns="http://www.tei-c.org/ns/1.0" xml:lang="fr">
74	103	<l xmlns="http://www.tei-c.org/ns/1.0">
108	143	<l xmlns="http://www.tei-c.org/ns/1.0">
148	180	<l xmlns="http://www.tei-c.org/ns/1.0">
185	220	<l xmlns="http://www.tei-c.org/ns/1.0">
225	272	<l xmlns="http://www.tei-c.org/ns/1.0">
277	305	<l xmlns="http://www.tei-c.org/ns/1.0">
310	338	<l xmlns="http://www.tei-c.org/ns/1.0">
343	387	<l xmlns="http://www.tei-c.org/ns/1.0">
